- id: sort-pyproject
  name: sort-pyproject
  description: Sort dependencies in pyproject.toml alphabetically.
  entry: sort-pyproject
  language: python
  language_version: python3
  files: ^pyproject.toml$
  pass_filenames: false
